# MySQL.  Versions 4.1 and 5.0 are recommended.

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railstouch_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railstouch_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railstouch_production
  pool: 5
  username: root
  password: railstouch

